dataset:
    RawDataPath: '/flexo/ComputationalMicroscopy/SpinningDisk/RawData/brainarchitecture'
    ProcessedPath:'/flexo/ComputationalMicroscopy/Processed/brainarchitecture'
    ImgDir:'2018_12_27_background_optimization_Nowakowski_slide'
    SmDir:'SMS_2018_1227_0138_3'
    BgDir:'BG_2018_1227_1311_1'
    BgDir_local:'BGS_2018_1227_1802_2'
processing:
    outputChann:['Transmission', 'Retardance', 'Orientation', 'Scattering', 'Retardance+Orientation',
                   'Transmission+Retardance+Orientation', 'Scattering+Orientation', 'Retardance+Fluorescence',
                   '405', '568', '640']
    circularity:'rcp'
    bgCorrect:'Local_filter'
    flatField:False
    batchProc:False
plotting:
    norm:True
       

